# Lists Countries in NATO
countries = {
    'Albania'
    'Belgium'
    'Bulgaria'
    'Canada'
    'Croatia'
    'Czech Republic'
    'Denmark'
    'Estonia'
    'France'
    'Germany'
    'Greece'
    'Hungary'
    'Iceland'
    'Italy'
    'Latvia'
    'Lithuania'
    'Luxembourg'
    'Montenegro'
    'Netherlands'
    'Norway'
    'Poland'
    'Portugal'
    'Romania'
    'Slovakia'
    'Slovenia'
    'Spain'
    'Turkey'
    'The United Kingdom'
    'The United States'
}

# List the capital of each country in NATO
